name: 'Auto Assign Action'
description: 'Add reviewers to pull requests when pull requests are opened.'
author: 'abhi thakre'
inputs:
  repo-token:
    description: 'A token for the repo'
    default:  ${{ secrets.MYGITHUB_TOKEN }}
    required: false
  configuration-path:
    description: 'A path for the auto-assign configuration'
    default: '.github/auto_assign.yaml'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'user-plus'
  color: 'blue'
