name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: npm install
    - run: npm ci
    - run: npm run build
    - run: npm test
    - uses: actions/checkout@v1
      with:
        repo-token: ${{ secrets.MYGITHUB_TOKEN }}
        persons: "abhithakre"
        teams: "no-team"
        include-draft: false
        skip-with-manual-reviewers: 1
        
