name: "Test typescript-action"
on:
  pull_request:
  push:
    branches:
      - master
    

jobs:

  auto-assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Run assignment of reviewer team
        uses: actions/checkout@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          teamName: 'abc'
