name: 'Test'

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: setup node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: install
        run: npm install

      - name: build
        run: npm run build
        
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.1
        with:
          configuration-path: ".github/workflows/auto_assign.yml" # Only needed if you use something other than .github/auto_assign.yml
