name: "Auto Assign"
on:
  pull_request:
  push:
    branches:
      - master
      

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1


    - uses: ./
      with: 
        repo-token: ${{ secrets.MYGITHUB_TOKEN }}
        persons: "abhithakre"
        teams: "abc"
        include-draft: false
        skip-with-manual-reviewers: 1
